#!/bin/sh

cd /
echo "Iniciando"
# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
mount /dev
#mount /dev/pts
#Start udev
/etc/init.d/udev start

#Load USB modules
modprobe ohci-hcd
modprobe usb-storage

#exec /bin/bash
#sleep 5
echo -n "Aguardando pendrive USB."
DEVPATH=/dev/sda1
#n=1
until test -e $DEVPATH
do
	sleep 1
	echo -n "."
	#[ n -eq 15 ] && e2fsck /dev/sda1
done
echo "OK"

# Mount the root filesystem.
#e2fsck /dev/sda1
mount /dev/sda1 /mnt

/etc/init.d/udev stop
/etc/init.d/portmap stop
# pkill -9 portmap

#exec /bin/bash

cd /mnt
mkdir -p tmp_old
pivot_root . tmp_old
/bin/umount tmp_old/proc
#/bin/umount tmp_old/sysfs
/bin/mount -n --move tmp_old/dev /dev
/bin/mount -t proc proc /proc
/bin/mount -t sysfs none /sys
#/bin/umount tmp

echo
echo "------- INICIANDO DEBIAN SQUEEZE (via pen drive USB) ------"
echo

exec /usr/sbin/chroot . /bin/sh <<- EOF
  /bin/umount tmp_old
  #/bin/bash
  exec /sbin/init
EOF

#/bin/bash

#exec /bin/bash

