/******************************************************************************

Project:           Cross-Platform GUI for lpc21isp, a command line ISP for
                   NXP LPC1000 / LPC2000 family and Analog Devices ADUC70xx
                   * This program has lpc21isp compiled into it.

Compiler:          Microsoft VC 6/7, Microsoft VS2008, Microsoft VS2010,
                   GCC Cygwin, GCC Linux, GCC ARM ELF

Author:            Moses McKnight (moses@texband.net)

Copyright:         (c) Moses McKnight 2011, All rights reserved

    This file is part of flpcui.

    flpcui is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    flpcui is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    and GNU General Public License along with flpcui.
    If not, see <http://www.gnu.org/licenses/>.
*/
// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef flpcui_h
#define flpcui_h
#include <FL/Fl.H>
#include <string>
#include <FL/Fl_Double_Window.H>
extern void on_exit(Fl_Double_Window*, void*);
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void on_open_file(Fl_Button*, void*);
extern void on_program(Fl_Button*, void*);
#include <FL/Fl_Output.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Menu_Bar.H>

class lpcprog_ui {
public:
  std::string default_dir; 
  lpcprog_ui();
  Fl_Double_Window *win;
  Fl_Output *file_input;
  Fl_Choice *port_choice;
  Fl_Choice *baud_choice;
  static Fl_Menu_Item menu_baud_choice[];
  Fl_Check_Button *erase_check;
  Fl_Check_Button *verify_check;
  Fl_Choice *chip_choice;
  static Fl_Menu_Item menu_chip_choice[];
  Fl_Int_Input *osc_speed_input;
  Fl_Check_Button *control_check;
  Fl_Check_Button *swap_check;
  Fl_Check_Button *invert_check;
  Fl_Check_Button *hdup_check;
  Fl_Choice *debug_choice;
  static Fl_Menu_Item menu_debug_choice[];
  Fl_Text_Display *dbg_text;
  static Fl_Menu_Item menu_[];
  void show(int argc, char **argv);
  void write_prefs();
  void read_prefs();
};
void on_exit(Fl_Widget*, void*);
extern lpcprog_ui *ui;
#endif
